### ISSUE TITLE
Google Map API - Change to OSM 

### ISSUE THREAD

**Issue by iamnunocaldeira** [paraboul/mapchecking#1]
hi Anthony cheers for your website MapChecking. However with the recent Google Maps API changes I would suggest you to use OpenStreetMap via Openlayers or other free option. It's displaying an annoying "for developing purposes only" on the map now.

**Comment by paraboul** [comment]
Closing this as MapChecking is now supported by Google as a "news and media" organisationion

**Comment by gy-mate** [comment]
I would still recommend making OSM (i.e. OpenFreeMap) a background layer option because it often has more detailed data in cities compared to Google Maps.
